theme: jekyll-theme-cayman
title: Assembleia Martin Luther
description: "Sala de assembleia: https://pml.lt.coop.br/AssembleiaPML"
links:
  site: https://www.luteranos.com.br/paroquia/martin-luther-rio-de-janeiro-centro
  youtube: https://www.youtube.com/c/paroquiamartinluther
